on: push
name: Default workflow for pushes
jobs:
  mvn-java-11:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      uses: docker://maven:3.6.1-jdk-11
      with:
        entrypoint: mvn
        args: -U -B verify
  mvn-java-8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      uses: docker://maven:3.6.1-jdk-8
      with:
        entrypoint: mvn
        args: -U -B verify
